### ISSUE TITLE
"wasm-c" example run into exception

### ISSUE THREAD

**Issue by tmm360** [stackpath/serverless-scripting-examples#44]
I've tried to run the "wasm-c" example from repository following instructions, I've compiled and deployed, but on production I get "Critical error.".

I've so tried to compile it without optimization (for debug scope) and run it on https://sandbox.edgeengine.io/, but I receive this error:

```
Error: TypeError: instance._fib is not a function
    at handleRequest (<script>:631:39)
    at addEventListener (<script>:635:21)
    at t.fireFetchEvent (webpack:///src/events.ts:160:1)
    at fetchCallback (/v8-scriptengine/packages/v8-scriptengine/build/server.js:110:31)
```

**Comment by klaude** [comment]
Thanks for the stack trace! I'm getting the same error. Nothing stands out as super wrong. I'll throw some debug statements around and track down the cause.

**Comment by klaude** [comment]
Hey man, we're still looking into this. The example looks right, and it worked when it was written. I'm checking to see if there were Emscripten changes from then to now that could account for it. I may also see if I can pull a copy of our v8 engine that we use in production for a little extra internal debugging. Thanks for your patience!

**Comment by tmm360** [comment]
To have a copy of the production engine could very cool for local development and understanding!

**Comment by klaude** [comment]
I agree! But I believe we have some secret sauce in there that prevents distribution. 😢

**Comment by klaude** [comment]
Thanks for waiting on me. I'm a bit of a novice working in our v8 engine, and I'm afraid I haven't made much headway. I've escalated this to our serverless engineers for further investigation. I'll keep this issue open and let you know when I hear more. Thanks!
